version: '3.4'
services:
  wulkanizacja.service.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wulkanizacja.Service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5884:8080"
